In [1]:
# Import pandas library
import pandas as pd

In [2]:
planet = pd.DataFrame({
    'Planet':['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'radius_km': [2490, 6052, 6371, 33390, 69911, 58232, 25362, 24622],
    'Moons': [0, 0, 1, 2, 80, 83, 27, 14]
})

planet

    Planet  radius_km  Moons
0  Mercury       2490      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars      33390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [19]:
clothes = pd.DataFrame({'type': ['pants', 'shirt', 'shirt', 'pants', 'shirt', 'pants'],
                       'color': ['red', 'blue', 'green', 'blue', 'green', 'red'],
                       'price_usd': [20, 35, 50, 40, 100, 75],
                       'mass_g': [125, 440, 680, 200, 395, 485]})


clothes

    type  color  price_usd  mass_g
0  pants    red         20     125
1  shirt   blue         35     440
2  shirt  green         50     680
3  pants   blue         40     200
4  shirt  green        100     395
5  pants    red         75     485

In [20]:
clothes.groupby(['type', 'color']).size()

type   color
pants  blue     1
       red      2
shirt  blue     1
       green    2
dtype: int64

In [23]:
clothes.groupby('color').agg({'price_usd': ['mean', 'max'],
                             'mass_g': ['mean', 'max']})

      price_usd      mass_g
           mean  max   mean  max
color
blue       37.5   40  320.0  440
green      75.0  100  537.5  680
red        47.5   75  305.0  485

In [24]:
grouped = clothes.groupby(['color', 'type']).agg(['mean', 'min'])
grouped

            price_usd     mass_g
                 mean min   mean  min
color type
blue  pants      40.0  40  200.0  200
      shirt      35.0  35  440.0  440
green shirt      75.0  50  537.5  395
red   pants      47.5  20  305.0  125

In [17]:
data = {'EmployeeID':[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
    'Profession':['Data Analyst', 'Data Scientist', 'Software Engineer',
              'Data Architect','Data Analyst', 'Business Analyst', 'Data Analyst',
              'Data Scientist', 'Software Engineer', 'Data Analyst'],
    'Firstname':['Mary', 'Sarah', 'John', 'Abel', 'Abaraham',
             'Mbappe', 'Elon', 'Chloe', 'Stone', 'Green'],
   'Lastname':['Smith', 'Jones', 'wick', 'Light', 'Blessing',
            'Saul', 'Orbita', 'Mat', 'Kelvin', 'Dino'],
    'Age':[24, 27, 30, 26, 25, 28, 29, 32, 35, 28],
    'Salary':['$50,000', '$75,000', '$80,000', '$65,000', '$55,000', '$60,000',
          '$70,000', '$85,000', '$90,000', '$73,000']}

employee = pd.DataFrame(data)

In [ ]:
print(data.keys())

dict_keys(['EmployeeID', 'Profession', 'Firstname', 'Lastname', 'Age', 'Salary'])

In [ ]:
print(list(data.keys()))

['EmployeeID', 'Profession', 'Firstname', 'Lastname', 'Age', 'Salary']

In [ ]:
for k, v in data.items():
    print(k, v, sep=':')

EmployeeID:[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Profession:['Data Analyst', 'Data Scientist', 'Software Engineer', 'Data Architect', 'Data Analyst', 'Business Analyst', 'Data Analyst', 'Data Scientist', 'Software Engineer', 'Data Analyst']
Firstname:['Mary', 'Sarah', 'John', 'Abel', 'Abaraham', 'Mbappe', 'Elon', 'Chloe', 'Stone', 'Green']
Lastname:['Smith', 'Jones', 'wick', 'Light', 'Blessing', 'Saul', 'Orbita', 'Mat', 'Kelvin', 'Dino']
Age:[24, 27, 30, 26, 25, 28, 29, 32, 35, 28]
Salary:['$50,000', '$75,000', '$80,000', '$65,000', '$55,000', '$60,000', '$70,000', '$85,000', '$90,000', '$73,000']

In [ ]:
employee.head(3)

   EmployeeID         Profession Firstname Lastname  Age   Salary
0         100       Data Analyst      Mary    Smith   24  $50,000
1         101     Data Scientist     Sarah    Jones   27  $75,000
2         102  Software Engineer      John     wick   30  $80,000

In [ ]:
employee.tail(1)

   EmployeeID    Profession Firstname Lastname  Age   Salary
9         109  Data Analyst     Green     Dino   28  $73,000

In [ ]:
employee.sample(4)

   EmployeeID         Profession Firstname  Lastname  Age   Salary
2         102  Software Engineer      John      wick   30  $80,000
4         104       Data Analyst  Abaraham  Blessing   25  $55,000
5         105   Business Analyst    Mbappe      Saul   28  $60,000
8         108  Software Engineer     Stone    Kelvin   35  $90,000

In [18]:
employee

   EmployeeID         Profession Firstname  Lastname  Age   Salary
0         100       Data Analyst      Mary     Smith   24  $50,000
1         101     Data Scientist     Sarah     Jones   27  $75,000
2         102  Software Engineer      John      wick   30  $80,000
3         103     Data Architect      Abel     Light   26  $65,000
4         104       Data Analyst  Abaraham  Blessing   25  $55,000
5         105   Business Analyst    Mbappe      Saul   28  $60,000
6         106       Data Analyst      Elon    Orbita   29  $70,000
7         107     Data Scientist     Chloe       Mat   32  $85,000
8         108  Software Engineer     Stone    Kelvin   35  $90,000
9         109       Data Analyst     Green      Dino   28  $73,000

In [ ]:
# Create a column call Name
employee['Name'] = employee['Firstname'] + ' ' + employee['Lastname']
employee.head(3)

   EmployeeID         Profession Firstname Lastname  Age   Salary         Name
0         100       Data Analyst      Mary    Smith   24  $50,000   Mary Smith
1         101     Data Scientist     Sarah    Jones   27  $75,000  Sarah Jones
2         102  Software Engineer      John     wick   30  $80,000    John wick

In [ ]:
employee = employee[['EmployeeID', 'Profession', 'Firstname', 'Lastname', 'Name', 'Age', 'Salary']]
employee.head(2)

   EmployeeID      Profession Firstname Lastname         Name  Age   Salary
0         100    Data Analyst      Mary    Smith   Mary Smith   24  $50,000
1         101  Data Scientist     Sarah    Jones  Sarah Jones   27  $75,000

In [ ]:
print(employee.dtypes)

EmployeeID     int64
Profession    object
Firstname     object
Lastname      object
Name          object
Age            int64
Salary        object
dtype: object

In [ ]:
employee.Salary

0    $50,000
1    $75,000
2    $80,000
3    $65,000
4    $55,000
5    $60,000
6    $70,000
7    $85,000
8    $90,000
9    $73,000
Name: Salary, dtype: object

In [ ]:
employee['Salary']

0    $50,000
1    $75,000
2    $80,000
3    $65,000
4    $55,000
5    $60,000
6    $70,000
7    $85,000
8    $90,000
9    $73,000
Name: Salary, dtype: object

In [ ]:
employee.head(2)

   EmployeeID      Profession Firstname Lastname         Name  Age   Salary
0         100    Data Analyst      Mary    Smith   Mary Smith   24  $50,000
1         101  Data Scientist     Sarah    Jones  Sarah Jones   27  $75,000

In [ ]:
employee['Salary'] = (employee['Salary'].str.replace('$', '', regex = False)
                    .str.replace(',', '')
                    .astype('int'))

In [ ]:
employee.head(2)

   EmployeeID      Profession Firstname Lastname         Name  Age  Salary
0         100    Data Analyst      Mary    Smith   Mary Smith   24   50000
1         101  Data Scientist     Sarah    Jones  Sarah Jones   27   75000

In [ ]:
employee.dtypes

EmployeeID     int64
Profession    object
Firstname     object
Lastname      object
Name          object
Age            int64
Salary         int64
dtype: object

In [ ]:
print(employee.Salary.mean())

70300.0

In [ ]:
print(f"Average salary of the employee is ${employee.Salary.mean():,.0f}")

Average salary of the employee is $70,300

In [ ]:
print('Maximum Salary:', employee['Salary'].max())
print('Minimum salary:', employee['Salary'].min())
print('Number of employee:', employee['Salary'].count())

Maximum Salary: 90000
Minimum salary: 50000
Number of employee: 10

In [ ]:
avg_salary_by_profession = employee.groupby('Profession')['Salary'].mean()
avg_salary_by_profession

Profession
Business Analyst     60000.0
Data Analyst         62000.0
Data Architect       65000.0
Data Scientist       80000.0
Software Engineer    85000.0
Name: Salary, dtype: float64

In [ ]:
employee_agg = employee.groupby('Profession')['Salary'].agg(['count', 'mean', 'max', 'min'])
employee_agg

                   count     mean    max    min
Profession
Business Analyst       1  60000.0  60000  60000
Data Analyst           4  62000.0  73000  50000
Data Architect         1  65000.0  65000  65000
Data Scientist         2  80000.0  85000  75000
Software Engineer      2  85000.0  90000  80000

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
sns.set(color_codes=True,
        rc = {

        })